//
//  ProfanityFilter.swift
//  MiniMate
//
//  Created by Garrett Butchko on 6/11/25.
//

import SwiftUI

struct ProfanityFilter {
    static let blockedWords: Set<String> = [
        "anal", "arse", "ass", "bastard", "bawdy", "bitch", "blow", "bollock", "boner", "boob",
        "booty", "bugger", "bullshit", "butt", "cameltoe", "carpet", "chink", "choad", "clit", "cluster",
        "cock", "coon", "cooch", "cooter", "crap", "cum", "cunt", "damn", "degenerate", "dick",
        "dildo", "dipshit", "douche", "dyke", "fag", "fanny", "feltch", "fingerbang", "fist", "flamer",
        "freak", "fuck", "gangbang", "gay", "goatse", "goddamn", "gook", "grope", "handjob", "hardcore",
        "hoe", "homo", "honkey", "horny", "hump", "jack", "jap", "jerk", "jigaboo", "jizz",
        "kike", "kkk", "kunt", "labia", "lesbo", "lezzie", "lust", "masturb", "milf", "minge",
        "molest", "motherfuck", "muff", "mung", "nazi", "negro", "nig", "nutsack", "orgasm", "paki",
        "panty", "pecker", "penis", "pervert", "phag", "piss", "poon", "porn", "prick", "pube",
        "puss", "queef", "queer", "quim", "rape", "raunch", "rectum", "retard", "rim", "sack",
        "sadist", "schlong", "scrote", "scum", "semen", "sex", "shag", "shit", "skank", "skeet",
        "slut", "smeg", "smut", "snatch", "spaz", "spic", "spooge", "suck", "suckmy", "swallow",
        "teabag", "testicle", "tit", "toke", "tosser", "turd", "twat", "vag", "vagina", "vibe",
        "vibrator", "vulva", "wank", "wetback", "whore", "womb", "wop", "xxx", "yaoi", "yiffy",
        "zoophile", "zoosex", "abuse", "addict", "anus", "bang", "beaver", "beefcurtain", "bimbo", "blowjob",
        "bodily", "boink", "bonk", "bootie", "brutal", "bukake", "bull", "camel", "cheeks", "climax",
        "cocky", "condom", "corrupt", "crotch", "crude", "cummer", "cunning", "curs", "cutter", "dammit",
        "deepthroat", "degrade", "deviant", "diaper", "dirtypillows", "dominatrix", "dragqueen", "ejacul", "enema", "erect",
        "escort", "excrement", "expose", "extort", "fetish", "filth", "flesh", "fondl", "fornic", "g-spot",
        "genital", "groin", "gypsy", "hardon", "hentai", "hooker", "horn", "hustler", "incest", "innuendo",
        "intercourse", "jiggle", "kama", "kinky", "kissing", "latex", "lecher", "lick", "lingerie", "loins",
        "lube", "lusty", "malestimulation", "manhood", "masochist", "meatstick", "menstru", "miniskirt", "missionary", "moan",
        "molest", "mooch", "moron", "nasty", "nipple", "nookie", "nudity", "obscene", "orifice", "orgy",
        "panties", "pantyhose", "peep", "penetrat", "phallus", "playboy", "pole", "pornhub", "porno", "prostitut",
        "pubic", "puke", "pummel", "raunchy", "rear", "rectal", "rubber", "scat", "seduce", "sensual",
        "sewage", "shame", "shlong", "shove", "shower", "shut", "silly", "slapper", "sleaze", "slink",
        "slope", "smack", "snort", "sodom", "softcore", "spank", "spasm", "spit", "splooge", "spreader",
        "squeeze", "stiff", "strip", "stroke", "stud", "submissive", "sultry", "swine", "syringe", "taint",
        "tease", "tempt", "thong", "tight", "titty", "topless", "tramp", "transvestite", "trollop", "tush",
        "twerk", "undress", "urinal", "urinate", "urinat", "vibrator", "virgin", "voyeur", "wank", "wax",
        "wedge", "wet", "whip", "whitetrash", "wild", "xrate", "yank", "yeast", "zipper", "zits",
        "abortion", "affair", "arse", "asphyx", "babes", "backdoor", "ballgag", "bareback", "bazoom", "bdsm",
        "beast", "beej", "biatch", "bimbo", "bind", "bisex", "blackface", "blow", "bod", "boink",
        "bondage", "bootlick", "bottom", "bra", "breast", "brothel", "bulge", "cage", "carne", "chain",
        "cheek", "clench", "climax", "cling", "clown", "cockpit", "come", "consent", "contracept", "cuddle",
        "cunniling", "defile", "desire", "devour", "dirty", "discharge", "dominate", "donkey", "drench", "drip",
            "anal",
            "ana1",
            "ana|",
            "an@l",
            "an@1",
            "arse",
            "ars3",
            "ar$e",
            "ar$3",
            "ar5e",
            "ass",
            "as$",
            "as5",
            "a$s",
            "a$$",
            "bastard",
            "bast@rd",
            "bast4rd",
            "bas7ard",
            "bas7@rd",
            "bitch",
            "bitc#",
            "bit(h",
            "bit(#",
            "bi7ch",
            "blow",
            "bl0w",
            "b1ow",
            "b10w",
            "b|ow",
            "boner",
            "bon3r",
            "b0ner",
            "b0n3r",
            "8oner",
            "boob",
            "boo8",
            "bo0b",
            "bo08",
            "b0ob",
            "butt",
            "but7",
            "but+",
            "bu7t",
            "bu77",
            "clit",
            "cli7",
            "cli+",
            "cl1t",
            "cl17",
            "cock",
            "coc|<",
            "co(k",
            "co(|<",
            "c0ck",
            "cum",
            "cvm",
            "(um",
            "(vm",
            "cunt",
            "cun7",
            "cun+",
            "cvnt",
            "cvn7",
            "dick",
            "dic|<",
            "di(k",
            "di(|<",
            "d1ck",
            "dildo",
            "dild0",
            "di1do",
            "di1d0",
            "di|do",
            "fag",
            "fa9",
            "f@g",
            "f@9",
            "f4g",
            "fanny",
            "f@nny",
            "f4nny",
            "fuck",
            "fuc|<",
            "fu(k",
            "fu(|<",
            "fvck",
            "gay",
            "g@y",
            "g4y",
            "9ay",
            "9@y",
            "goddamn",
            "godd@mn",
            "godd4mn",
            "g0ddamn",
            "g0dd@mn",
            "hoe",
            "ho3",
            "h0e",
            "h03",
            "#oe",
            "homo",
            "hom0",
            "h0mo",
            "h0m0",
            "#omo",
            "horny",
            "h0rny",
            "#orny",
            "#0rny",
            "jack",
            "jac|<",
            "ja(k",
            "ja(|<",
            "j@ck",
            "jizz",
            "jiz2",
            "ji2z",
            "ji22",
            "j1zz",
            "kike",
            "kik3",
            "ki|<e",
            "ki|<3",
            "k1ke",
            "kunt",
            "kun7",
            "kun+",
            "kvnt",
            "kvn7",
            "labia",
            "labi@",
            "labi4",
            "lab1a",
            "lab1@",
            "lesbo",
            "lesb0",
            "les8o",
            "les80",
            "le$bo",
            "lust",
            "lus7",
            "lus+",
            "lu$t",
            "lu$7",
            "milf",
            "mi1f",
            "mi|f",
            "m1lf",
            "m11f",
            "molest",
            "moles7",
            "moles+",
            "mole$t",
            "mole$7",
            "muff",
            "mvff",
            "nazi",
            "naz1",
            "naz!",
            "naz|",
            "na2i",
            "negro",
            "negr0",
            "ne9ro",
            "ne9r0",
            "n3gro",
            "nig",
            "ni9",
            "n1g",
            "n19",
            "n!g",
            "orgasm",
            "orga$m",
            "orga5m",
            "org@sm",
            "org@$m",
            "panty",
            "pan7y",
            "pan+y",
            "p@nty",
            "p@n7y",
            "penis",
            "peni$",
            "peni5",
            "pen1s",
            "pen1$",
            "piss",
            "pis$",
            "pis5",
            "pi$s",
            "pi$$",
            "porn",
            "p0rn",
            "prick",
            "pric|<",
            "pri(k",
            "pri(|<",
            "pr1ck",
            "pube",
            "pub3",
            "pu8e",
            "pu83",
            "pvbe",
            "puss",
            "pus$",
            "pus5",
            "pu$s",
            "pu$$",
            "queer",
            "que3r",
            "qu3er",
            "qu33r",
            "qveer",
            "rape",
            "rap3",
            "r@pe",
            "r@p3",
            "r4pe",
            "rectum",
            "rectvm",
            "rec7um",
            "rec7vm",
            "rec+um",
            "retard",
            "ret@rd",
            "ret4rd",
            "re7ard",
            "re7@rd",
            "rim",
            "r1m",
            "r!m",
            "r|m",
            "sadist",
            "sadis7",
            "sadis+",
            "sadi$t",
            "sadi$7",
            "scum",
            "scvm",
            "s(um",
            "s(vm",
            "$cum",
            "semen",
            "sem3n",
            "s3men",
            "s3m3n",
            "$emen",
            "sex",
            "s3x",
            "$ex",
            "$3x",
            "5ex",
            "shit",
            "shi7",
            "shi+",
            "sh1t",
            "sh17",
            "slut",
            "slu7",
            "slu+",
            "slvt",
            "slv7",
            "spaz",
            "spa2",
            "sp@z",
            "sp@2",
            "sp4z",
            "spic",
            "spi(",
            "sp1c",
            "sp1(",
            "sp!c",
            "suck",
            "suc|<",
            "su(k",
            "su(|<",
            "svck",
            "swallow",
            "swall0w",
            "swal1ow",
            "swal10w",
            "swal|ow",
            "teabag",
            "teaba9",
            "teab@g",
            "teab@9",
            "teab4g",
            "tit",
            "ti7",
            "ti+",
            "t1t",
            "t17",
            "turd",
            "tvrd",
            "7urd",
            "7vrd",
            "+urd",
            "twat",
            "twa7",
            "twa+",
            "tw@t",
            "tw@7",
            "vag",
            "va9",
            "v@g",
            "v@9",
            "v4g",
            "vagina",
            "vagin@",
            "vagin4",
            "vag1na",
            "vag1n@",
            "whore",
            "whor3",
            "wh0re",
            "wh0r3",
            "w#ore",
            "wop",
            "w0p",
            "xxx",
            "yaoi",
            "yao1",
            "yao!",
            "yao|",
            "ya0i",
            "zoophile",
            "zoophil3",
            "zoophi1e",
            "zoophi13",
            "zoophi|e"
        ]
    
    static func containsBlockedWord(_ text: String) -> Bool {
        return blockedWords.contains { text.localizedCaseInsensitiveContains($0) }
    }
}
